### ISSUE TITLE
Fail to close database after creating convenience function using checkout_spinedb() 

### ISSUE THREAD

**Issue by zhenmin1993** [Spine-project/SpineInterface.jl#1]
Julia 1.1
SpineInterface v0.1.0 #master
PyCall v1.91.2

The issue is that we failed to close/unlock the database after creating convenience function using checkout_spinedb(). The related error message is:

ERROR: LoadError: IOError: unlink: resource busy or locked (EBUSY)
Stacktrace:
 [1] uv_error at .\libuv.jl:85 [inlined]
 [2] unlink(::String) at .\file.jl:727
 [3] #rm#9(::Bool, ::Bool, ::Function, ::String) at .\file.jl:253
 [4] rm at .\file.jl:245 [inlined].

Thanks!

**Comment by manuelma** [comment]
thanks @zhenmin1993 

Does it happen when you call `checkout_spinedb()`, or after? Can you provide a full program?

**Comment by manuelma** [comment]
I believe this problem is the same as reported in Spine-project/Spine-Database-API#3

**Comment by zhenmin1993** [comment]
> thanks @zhenmin1993
> 
> Does it happen when you call `checkout_spinedb()`, or after? Can you provide a full program?

Hello @manuelma , it happens after I call `checkout_spinedb()`, and I was also trying to remove the file afterwards. And it is indeed exactly the same issue, I'm actually using @hhoeschle's code. 

Below is a simple case that would give the error:

`using Logging
Base.CoreLogging.global_logger(Logging.ConsoleLogger(stderr, Base.CoreLogging.Info))#Base.CoreLogging.Error))

using SpineInterface
using PyCall
test_data_path = joinpath(@__DIR__)
basic_test_db = joinpath(test_data_path, "database_Basic.sqlite")
#basic_test_db =nothing
basic_test_db_url = "sqlite:///$basic_test_db"
sa = pyimport("spinedb_api")

sa.create_new_spine_database(basic_test_db_url)
db_map = sa.DatabaseMapping(basic_test_db_url, upgrade=true)
db_map.reset_mapping()



results, time_load_db = @timed checkout_spinedb(basic_test_db_url, upgrade=true)
@info "Spine DB loaded in $time_load_db seconds"

db_map.session.close()
rm(basic_test_db)
`

**Comment by Tasqu** [comment]
I believe this issue is outdated. Care to confirm, @manuelma ?
