### ISSUE TITLE
Error returning relationships with limited amount of objects

### ISSUE THREAD

**Issue by hhoeschle** [Spine-project/SpineInterface.jl#2]
Hi,

I discovered an issue when returning relationships from the database:

Following example shows the issue:
```julia
@show Agents__Technologies__Spatials(Agents=:EnergyProducerAgent2, _compact=false)
@show Agents__Technologies__Spatials(Agents=:EnergyProducerAgent2)
```
so I try to return all relationships for which the Agents is EnergyProducerAgent2.

However the second line produces an error linked to the creation of the `NamedTuple` in the following line:

https://github.com/Spine-project/SpineInterface.jl/blob/9f5d256b704119ae82f3ae926c52d29cfa8ef67e/src/types.jl#L307

I could solve the issue by adapting the line to (i.e. creating a tuple of Symbols first):
```julia
unique(NamedTuple{tuple(head...)}([x[k] for k in head]) for x in result)
```

Would be nice if you could make a commit including this change. It might also occur at another place. 

Greetings,
Hanspeter

**Comment by manuelma** [comment]
Good catch @hhoeschle 

Will push your fix now. Thanks!

**Comment by Tasqu** [comment]
This issue has been fixed.
