### ISSUE TITLE
Problems with TimeSlice names

### ISSUE THREAD

**Issue by hhoeschle** [Spine-project/SpineInterface.jl#5]
Hallo, 

we use the SpineInterface to feed a model based on MCP reformulation using the [Complementarity](https://github.com/chkwon/Complementarity.jl) package.

The package uses `Meta.parse` to forward variable names to the model -> see [Link](https://github.com/chkwon/Complementarity.jl/blob/master/src/mcp.jl#L338)

There is a problem with the `...`in the representation of the TimeSlices

```julia
using Base.Meta
s = "price[CentralizedCapacityMarket,r01_z01,2010-01-01T00:00:00...2011-01-01T00:00:00,s01]"
Meta.parse(s) # error

s = "price[CentralizedCapacityMarket,r01_z01,2010-01-01T00:00:00||2011-01-01T00:00:00,s01]"
Meta.parse(s) # working

```

Would be nice if we could find a solution to that in SpineInterface...

Thanks
Hanspeter

**Comment by hhoeschle** [comment]
Currently I fix it by the overwriting the method in the following way:

```julia
## Fix to TimeSlice name
Base.show(io::IO, time_slice::TimeSlice) = print(io, time_slice.start)
```

**Comment by Tasqu** [comment]
I believe this issue is outdated? Currently:
```julia
Base.show(io::IO, t::TimeSlice) = print(io, string(Dates.format(start(t), _df)), "~>", Dates.format(end_(t), _df))
```
so `...` is no longer used as far as I know.
