### ISSUE TITLE
Problem with comparison operators of TimeSlices

### ISSUE THREAD

**Issue by steffenkaminski** [Spine-project/SpineInterface.jl#6]
Following results seems unexpected to me
```

julia> ty1
2010-01-01T00:00:00~>2011-01-01T00:00:00

julia> t2
2010-01-01T01:00:00~>2010-01-01T02:00:00

julia> th1
2010-01-01T00:00:00~>2010-01-01T01:00:00
julia> ty1<=t2
true

julia> ty1<=th1
false

julia> ty1.start<=th1.start
true

julia> ty1<=t2
true

```

I would have expected:
```
julia> ty1<=th1
true

```

Is that behaviour wanted? @manuelma

**Comment by manuelma** [comment]
This is how TimeSlices compare:
```
Base.isless(a::TimeSlice, b::TimeSlice) = tuple(start(a), end_(a)) < tuple(start(b), end_(b))
```

So it's basically like comparing the tuples (start, end). In your example, `ty1` ends later than `th1` which results in the observed behavior, `ty1 > th1`. I think this is correct, but I'm open to discussion.

**Comment by steffenkaminski** [comment]
No, ok. That makes sense for me now. I was implicitly assuming that just the start times were considered, which is note the case.

**Comment by Tasqu** [comment]
Outdated, and there doesn't seem to be an actual issue here? Just some confusion about how timeslices are compared.
