### ISSUE TITLE
`TimePattern` treats everything as union regardless of definition

### ISSUE THREAD

**Issue by Tasqu** [Spine-project/SpineInterface.jl#70]
# Edit 2021-09-07

So it would seem that Spine DB API allows for distinguishing between union and intersects between the defined ranges: https://github.com/Spine-project/Spine-Database-API/blob/master/docs/source/parameter_value_format.rst

However, SpineInterface doesn't seem to get the memo and treats everything as union as highlighted in the original issue below.

# Original

Essentially, `TimePattern` is just a dictionary of `PeriodCollection`s mapped to values. At the moment, `TimePattern` is interpreted as extremely lenient, and I'm not sure if that's intended. I'll give an extremely simple example:

Consider a `TimePattern` with only one `PeriodCollection`
```julia
tp = Dict(PeriodCollection(;Y=[2000:2020], M=[1:6]) => 1.0)
```
so the year range is between 2000-2020, and the month range between January and June. At least to me, a definition like this seems like it indicates that months between January and June during the years 2000-2020 are attributed with the value 1.0.

**However, this is not the case at the moment.** Instead, accessing `tp` with any `TimeSlice` that includes a year between 2000-2020 *(regardless of the month)* or a month between 1 and 6 *(regardless of the year)* is interpreted as having a value of 1.0.

This behaviour is caused by how the `TimePatternParameterValue` is accessed:
```julia
function (p::TimePatternParameterValue)(t::TimeSlice)
    vals = [val for (tp, val) in p.value if overlaps(t, tp)]
    isempty(vals) && return nothing
    mean(vals)
end
```
where the `overlaps(t, tp)` function defines the values to be included. There:
```julia
function overlaps(t::TimeSlice, pc::PeriodCollection)
    funcs = Dict{Symbol,Function}(
        :Y => year,
        :M => month,
        :D => day,
        :WD => dayofweek,
        :h => hour,
        :m => minute,
        :s => second,
    )
    for name in fieldnames(PeriodCollection)
        field = getfield(pc, name)
        field === nothing && continue
        func = funcs[name]
        b = func(start(t)):func(end_(t))
        ### THE FOLLOWING `any()` ACCEPTS ANY OVERLAP! ###
        any(!isempty(intersect(a, b)) for a in field) && return true
        ###
    end
    false
end
```
where an overlap is detected as long as *any* field of the `PeriodCollection` overlaps the `TimeSlice`. Should this be changed to `all()`, so that the `TimeSlice` should match all the defined periods in order to be considered to "overlap" the `PeriodCollection`?

**Comment by jkiviluo** [comment]
I agree that this is too lenient and should be fixed.

**Comment by DillonJ** [comment]
I know in other implementations of this type of functionality, you have different _punctuation_ to indicate whether two conditions act as a union or an intersection. E.g. comma vs. semicolon. Are we sure we understand the expected syntax correctly? I know that this is documented in spinedb_api but not very well in the Toolbox user guide

**Comment by Tasqu** [comment]
Oh you're right, there is such a punctuation in `SpineDBAPI` https://github.com/Spine-project/Spine-Database-API/blob/master/docs/source/parameter_value_format.rst

However, the `SpineInterface` implementation doesn't seem to get the distinction, and it treats everything as union...

**Comment by DillonJ** [comment]
It so happens @soininen as in https://github.com/Spine-project/Spine-Toolbox/issues/1487#issuecomment-921630586 updated the parameter value editor documentation to better describe the expected syntax, and indeed, a semi-colon is needed for an intersection of ranges : https://spine-toolbox.readthedocs.io/en/latest/parameter_value_editor.html

However, it sounds like you've tested with a semi-colon and are observing incorrect behaviour?

**Comment by Tasqu** [comment]
@DillonJ I haven't tested it with a different syntax, but there's no `SpineInterface` code to handle intersections. In fact, the `TimePattern` type in `SpineInterface` doesn't even contain information about whether the `PeriodCollections` it contains are to be interpreted as unions or intersections. As such, there's no way the current implementation actually does what the Spine DB API  documentation claims.

**Comment by DillonJ** [comment]
@manuelma any thoughts on this? It would be nice to get this working within "Crunch Time" although I know you have mixed feelings about this concept :-)

**Comment by manuelma** [comment]
Hahaha. Not my favorite, but we can try something. We're just missing the union thing, right? Will take a look.

**Comment by DillonJ** [comment]
I think it's the intersection we're missing if I understand @Tasqu correctly

**Comment by Tasqu** [comment]
@manuelma @DillonJ Yeah, the current implementation assumes everything as union. Intersections are not handled according to the Spine DB API parameter specifications.
